"""Users, atms and issues table

Revision ID: 707ffec4c549
Revises: 
Create Date: 2022-10-21 23:01:46.198137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '707ffec4c549'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=512), nullable=True),
    sa.Column('email', sa.String(length=512), nullable=False),
    sa.Column('hashed_password', sa.String(length=60), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
