"""Add user roles

Revision ID: 92fc5e5cb8af
Revises: 707ffec4c549
Create Date: 2022-10-22 01:27:05.617562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92fc5e5cb8af'
down_revision = '707ffec4c549'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_internal_client', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('group', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'group')
    op.drop_column('users', 'is_internal_client')
    # ### end Alembic commands ###
